language: php
dist: jammy

php:
    - 8.1
    - 8.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
    directories:
        - $HOME/.composer/cache

env:
    matrix:
        - COMPOSER_FLAGS=""

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - vendor/bin/phpcs --standard=psr2 src/
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
